/// Flutter icons Aurora
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aurora
///      fonts:
///       - asset: fonts/Aurora.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Aurora {
  Aurora._();

  static const _kFontFam = 'Aurora';

  static const IconData analytics_7 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData analytics_12 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData analytics_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData analytics_16 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData archive = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData analytics_3 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData analytics = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData analytics_2 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData analytics_8 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData analytics_13 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData analytics_4 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData analytics_5 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData analytics_6 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData boxes = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData analytics_14 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData analytics_9 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData analytics_15 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData briefcase_2 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData briefcase_1 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData cutter = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData briefcase_3 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData curriculum = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData briefcase_4 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData desk_1 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData clipboard = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData desk = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData clip = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData coding = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData desk_2 = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData desk_lamp_1 = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData desk_lamp = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData desk_3 = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData diploma = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData diploma_1 = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData desk_chair = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData desk_chair_1 = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData diagram = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData laptop = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData marker = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData marker_1 = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData id_card_1 = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData notes = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData notebook = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData glue = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData eraser = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData notes_1 = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData id_card = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData office_chair = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData pen_1 = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData pen_2 = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData pencil_case = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData pen = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData push_pin = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData ruler = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData sharpener = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData push_pin_1 = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData stamp = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData stapler_remover = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData tape_1 = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData tea_cup = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData tape = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData tie = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData stapler_2 = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData stapler_1 = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData usb = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData stapler = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData projector = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData analytics_10 = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData analytics_11 = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData briefcase = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData attachment = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData analytics_17 = const IconData(0xe850, fontFamily: _kFontFam);
}
